apiVersion: legacy.k8s.keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: example-realm-user
  labels:
    app: external-sso
spec:
  realmSelector:
    matchLabels:
      app: external-sso
  user:
    username: "creds_user"
    firstName: "Creds"
    lastName: "User"
    email: "creds_user@redhat.com"
    enabled: True
    emailVerified: False
    credentials:
      - type: "password"
        value: "12345"
    realmRoles:
      - "offline_access"
    clientRoles:
      account:
        - "manage-account"
      realm-management:
        - "manage-users"
